INSERT INTO USERS (ID, VERSION, USERNAME, EMAIL, PASSWORD, ROLE) VALUES (0, 0, 'admin', 'admin@gmail.com', 'admin', 'ADMIN');

INSERT INTO ISSUES(ID,VERSION,DESCRIPTION,LOCATION,STATUS, TIMESTAMP) VALUES (0,0,'projektor elromlott','123','ADDED',CURRENT_TIMESTAMP())