CREATE MEMORY TABLE PUBLIC.USERS (
  ID       INTEGER      NOT NULL,
  VERSION  INTEGER      NOT NULL,
  EMAIL    VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  ROLE     VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL
)